server:
    port: 9090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/liuti
    username: root
    password: 122525
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.gaoyuan.liuti.entity
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
