server:
    port: 9090
spring:
  datasource:
    url: jdbc:mysql://10.10.1.250:3306/liuti
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.gaoyuan.liuti.entity
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true

