server:
    port: 9090
spring:
  datasource:
    url: ${MYSQL_ADDRESS:jdbc:mysql://10.10.1.250:3306/liuti}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:lnyj.net}
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.gaoyuan.liuti.entity
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
